#!/bin/bash -x

BASEDIR="/home/merengue"
PIDFILE="$BASEDIR/pid/betamerengue.pid"
VIRTUALENV=$BASEDIR/virtualenv/
SOCKET="$BASEDIR/sock/uwsgi.sock"
PROJECTNAME="demomerengueprojectorg"
LOGFILE="$BASEDIR/logs/betamerengue.uwsgi.log"

export LC_ALL=es_ES.UTF-8

function start {
   echo "Iniciando Merengue Beta:"
   cd $BASEDIR
   . $BASEDIR/virtualenv/bin/activate
   $BASEDIR/bin/uwsgi -p 2 -C -M 4 -A 4 -m -s $SOCKET -H $VIRTUALENV $PROJECTNAME.wsgi --pythonpath $BASEDIR/$PROJECTNAME/ --pidfile $PIDFILE -d $LOGFILE
}

function debug {
   echo "Modo depuracion Merengue Demo:"
   cd $BASEDIR
   . $BASEDIR/virtualenv/bin/activate
   $BASEDIR/bin/uwsgi -i -C -A 4 -m -s $SOCKET -H $VIRTUALENV $PROJECTNAME.wsgi --pythonpath $BASEDIR/$PROJECT/
}

function stop {
    echo "Terminando Merengue Beta:"
    pgrep uwsgi |xargs kill -9 2> /dev/null
}

case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;

    restart)
        stop
        start
    ;;

    debug)
        debug
    ;;

    *)
        echo "Usage: ~/scripts/betamerengue {start|stop|restart}"
        exit 1
    ;;
esac

exit 0

