#!/bin/bash -e

BASEDIR=/home/merengue
PROJECTDIR=$BASEDIR/demomerengueprojectorg

function enable_virtualenv {
    echo "Activando el entorno (virtualenv)"
    cd $BASEDIR
    . virtualenv/bin/activate
}

function update_code {
    echo "Actualizando el proyecto a la ultima revision"
    cd $PROJECTDIR
    svn up --username=$SVNUSERNAME --password=$SVNPASSWORD
}

function install_dependences {
    pip install -r http://svn.merengueproject.org/trunk/merengueproj/requirements.txt
}

function remove_pyc_files {
    echo "Eliminando ficheros precompilados de python"
    find -iname "*.pyc" -exec rm {}  \;
}
function migrate {
    echo "Actualizando la base de datos"
    cd $PROJECTDIR
    python manage.py syncdb --migrate
}

function servers_restart {
    echo "Reiniciando los servidores"
    cd $BASEDIR
    scripts/betamerengue restart
}

function sync_plugins_media {
    cd $PROJECTDIR
    python manage.py sync_plugins_media --link --all
}

function sync_apps_media {
    cd $PROJECTDIR
    python manage.py sync_apps_media --link
}

function update_doc {
    echo "Updating beta merengueprojectorg documentation"
    cd $BASEDIR/docs/
    svn up --username=$SVNUSERNAME --password=$SVNPASSWORD
    touch index.txt
    make html
}

enable_virtualenv
update_code
install_dependences
migrate
remove_pyc_files
sync_plugins_media
sync_apps_media
servers_restart
